# Generated by Django 2.2.1 on 2019-10-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(height_field=200, upload_to='', width_field=200)),
                ('description', models.TextField()),
                ('source', models.URLField()),
            ],
        ),
    ]
