# Generated by Django 2.2.2 on 2019-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('time', models.DateField()),
                ('gardensoil', models.BooleanField()),
                ('pottingmix', models.BooleanField()),
                ('raisedbed', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
