# Generated by Django 2.2.2 on 2019-06-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190623_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gardensoil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pottingmix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='raisedbed',
            field=models.BooleanField(default=False),
        ),
    ]
